baseURL: https://iriszhang.netlify.app/
languageCode: en-us
title: Portfolio website for Iris Yi-Chen Zhang
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: |-
      I am a current student in the Master in Financial Analysis Program at London Business School. For most of the time in my life, I grew up in Shanghai and Taiwan and had my undergraduate study at Boston.
#      AND RELEASED UNDER THE CREATIVE COMMONS.
    title: Greetings! My name is Yi-Chen Zhang. 
  blog: {}
  contact: 
    address: 
      - city: London
        country: United Kingdom
        street: Finchley Road
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: izhang.mfa2022@london.edu
        title: Email
    enable: yes
    phone:
      - phone: (+44) 751-876-6023
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: London Business School MFA
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
#      - icon: fa-twitter
#        label: Twitter
#        url: https://www.twitter.com
      - icon: fa-facebook
        label: Facebook
        url: https://www.facebook.com/profile.php?id=100007548132117
#      - icon: fa-instagram
#        label: Instagram
#        url: https://www.instagram.com
      - icon: fa-github
        label: GitHub
        url: https://github.com/IrisZhang98
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/yi-chen-zhang-5181a1207/
  image: ''
  name: Your name
  navigation:
    button1:
      - name: Get Started
        url: blogs
    button2:
      - name: Log In
        url: '#'
    links:
      - name: Home
        url: '#'
      - name: About Me
        url: blogs
      - name: Generic Blog
        url: blogs/ipsum
#      - name: Elements
#        url: elements.html
    menu: Menu
    subtitle: By HTML5 Up
    title: Forty
  tiles:
    enable: yes
    showcase:
      - image: pic10091.jpg
        subtitle: Photoes
        title: My Daily Life
        url: blogs/aliquam
      - image: pic10092.jpg
#        subtitle: 
        title: My work
        url: blogs/tempus
      - image: pic10093.jpg
#        subtitle: Lorem Etiam Nullam
        title: My pet
        url: blogs/magna
      - image: pic10094.jpg
#        subtitle: Nisl Sed Aliquam
        title: My Schools
        url: blogs/ipsum
      - image: pic10095.jpg
#        subtitle: Ipsum Dolor Sit Amet
        title: My Trips
        url: blogs/ipsum
      - image: pic06.jpg
#        subtitle: Feugiat Amet Tempus
        title: My Entertainments
        url: blogs/ipsum
  two:
    buttonText: Get Started
    enable: yes
    subtitle: "Nullam et orci eu lorem consequat tincidunt vivamus et sagittis libero.
      \r\n    Mauris aliquet magna magna sed nunc rhoncus pharetra. \r\n    Pellentesque
      condimentum sem. In efficitur ligula tate urna. Maecenas laoreet massa vel lacinia
      pellentesque lorem ipsum dolor. \r\n    Nullam et orci eu lorem consequat tincidunt.
      Vivamus et sagittis libero.\r\n    Mauris aliquet magna magna sed nunc rhoncus
      amet pharetra et feugiat tempus."
    title: Massa libero
    url: blogs
